server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
