server:
  port: 9090

spring:
  profiles:
    active: k8s
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
