server:
  port: 8883
  servlet:
    context-path: /course


spring:
  application:
    name: course-service
  profiles:
    active: k8s

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetchRegistry: true
    registerWithEureka: true
    registry-fetch-interval-seconds: 3