server:
  port: 8882
  servlet:
    context-path: /student

spring:
  profiles:
    active: k8s

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
