apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: microservices
  labels:
    app: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: mostafijurr/ms-course-service:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/microservice
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver


          readinessProbe:
            httpGet:
              path: /course/actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /course/actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: microservices
  labels:
    app: course-service
spec:
  selector:
    app: course-service
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
