server:
  port: 8761

spring:
  profiles:
    active: dev
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
