server:
  port: 8881
  servlet:
    context-path: /address

spring:
  profiles:
    active: 'k8s'
  application:
    name: address-service


eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetchRegistry: true
    registerWithEureka: true
    registry-fetch-interval-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
