name: Build & Push Service Docker Image

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Select the service to build'
        required: true
        type: choice
        options:
          - address
          - course
          - student
          - gateway
          - eureka
        default: address
      tag:
        description: 'Docker image tag (e.g., v1.0.0, latest)'
        required: true
        default: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mostafijurr/ms-${{ github.event.inputs.service }}
      IMAGE_TAG: ${{ github.event.inputs.tag }}
      SERVICE_DIR: ${{ github.event.inputs.service }}-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Gradle
        working-directory: ${{ env.SERVICE_DIR }}
        run: ./gradlew clean build -x test --no-daemon

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.SERVICE_DIR }}
          file: ./${{ env.SERVICE_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
